//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModels.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiscothequeDbEntities : DbContext
    {
        public DiscothequeDbEntities()
            : base("name=DiscothequeDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppCompanie> AppCompanies { get; set; }
        public virtual DbSet<AppDiscotheque> AppDiscotheques { get; set; }
        public virtual DbSet<AppDiscothequeCategorie> AppDiscothequeCategories { get; set; }
        public virtual DbSet<AppDiscothequeDetail> AppDiscothequeDetails { get; set; }
        public virtual DbSet<AppEmployee> AppEmployees { get; set; }
        public virtual DbSet<AppMusic> AppMusics { get; set; }
        public virtual DbSet<AppMusicDetail> AppMusicDetails { get; set; }
        public virtual DbSet<AppRol> AppRols { get; set; }
        public virtual DbSet<AppUser> AppUsers { get; set; }
    }
}
