//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModels.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiscothequeDbEntities : DbContext
    {
        public DiscothequeDbEntities()
            : base("name=DiscothequeDbEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppCompanie> AppCompanie { get; set; }
        public virtual DbSet<AppDiscotheque> AppDiscotheque { get; set; }
        public virtual DbSet<AppDiscothequeCategorie> AppDiscothequeCategorie { get; set; }
        public virtual DbSet<AppDiscothequeDetail> AppDiscothequeDetail { get; set; }
        public virtual DbSet<AppEmployee> AppEmployee { get; set; }
        public virtual DbSet<AppMusic> AppMusic { get; set; }
        public virtual DbSet<AppMusicDetail> AppMusicDetail { get; set; }
        public virtual DbSet<AppRol> AppRol { get; set; }
        public virtual DbSet<AppUser> AppUser { get; set; }
    }
}
